include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    library_private_types_in_public_api: ignore

linter:
  rules:
    avoid_print: false
    line_length: 100
    prefer_single_quotes: false
    require_trailing_commas: true
