name: Build and Release

on:
  workflow_dispatch:
    inputs:
      beta:
        type: boolean
        description: Beta release

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Doctor
        run: |
          flutter doctor -v

      - name: Extract version from pubspec.yaml
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build APKs
        run: flutter build apk --release --split-per-abi
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/flutter-apk/*.apk'
          tag: ${{ env.VERSION }}
          name: v${{ env.VERSION }}
          prerelease: ${{ inputs.beta }}
          allowUpdates: true
          removeArtifacts: true
          generateReleaseNotes: true
